AMP-42587 update segment plugin to use segment 4.1+
amplitude/itly-sdk-ios pull request #11
Opened 2021-10-09 04:27 UTC by qingzhuozhen

- Upgrade segment version
- Need to change the module name since the change introduced in [4.1.0](https://segment.com/docs/connections/sources/catalog/libraries/mobile/ios/changelog/#null)

2021-10-09 16:05 UTC, justin-fiedler approved these changes

2021-10-09 16:17 UTC, justin-fiedler requested changes
Just remembered we need to update the SegmentPlugin. Cartfile as well.

2021-10-09 17:22 UTC, qingzhuozhen commented
Good catch @justin-fiedler let me update for Carthage framework as well, didn't install it earlier since we normally just use Cocoapod

2021-10-10 17:04 UTC, justin-fiedler requested changes

2021-10-10 17:04 UTC, justin-fiedler commented on SegmentPlugin/Cartfile
> +github "segmentio/analytics-ios" ~> 4.1.0
Same here. `~> 4.1`

2021-10-11 05:25 UTC, qingzhuozhen commented on ItlySegmentPlugin.podspec
> +  spec.dependency "Analytics", "~> 4.1.0"
ok, will update that, hopefully they will honor the versioning and not bringing in breaking changes

2021-10-12 23:54 UTC, justin-fiedler approved these changes

2021-10-13 01:52 UTC, merged